---
- name: Setup NTP Service                                                                                                                                                       
  hosts: all 
  gather_facts: no                                                                                                                                                                       
  tasks:
  - name: "Set NTP Server"
    cisco.ios.ios_ntp:
      server: "{{ server }}"
      state: present
    loop: "{{ system.ntp.servers }}"
    loop_control:
      loop_var: server
      label: "{{ server }}"