---
- name: Setup NTP Service                                                                                                                                                       
  hosts: all                                                                                                                                                                        
  tasks:
    - name: debug
      debug:
        msg: "Test"